version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./certs:/etc/ssl/certs
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.my-app
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "5175:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - frontend
      - backend
