version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.my-app
    ports:
      - "5173:80"  # Mapeia a porta 80 do contêiner para a 5173 do host
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/nginx.conf
      - ./certs:/certs
    ports:
      - "5175:80"  # Mapeia a porta 80 do contêiner para a 5175 do host
      - "443:443"
    depends_on:
      - frontend
      - backend
