version: '3.8'

services:
  backend:
    build: ./backend  # Diretório do backend
    ports:
      - '3000:3000'  # Mapeia a porta 3000 do container para a porta 3000 do host (HTTPS)
    volumes:
      - ./backend:/app
      - ./certs:/etc/ssl  # Mapeia os certificados SSL para o container
    networks:
      - internal

  frontend:
    build: ./my-app  # Diretório do frontend agora é my-app
    ports:
      - '5173:5173'  # Mapeia a porta 5173 do container para a porta 5173 do host (HTTPS)
    volumes:
      - ./my-app:/app
      - ./certs:/etc/ssl  # Mapeia os certificados SSL para o container
    networks:
      - internal

networks:
  internal:
    driver: bridge
