version: '3.8'
networks:
  internal:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - ./certs/selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
    networks:
      - internal

  frontend:
    build: ./my-app
    ports:
      - '5173:5173'
    volumes:
      - ./my-app:/app
      - ./certs/selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./certs/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
    networks:
      - internal