version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    networks:
      - my-network

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
    networks:
      - my-network
    environment:
      - VITE_API_URL=https://mfgsvr3:3000

networks:
  my-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data:
