version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network
    volumes:
      - backend-data:/app/backend-data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.my-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my-network
    environment:
      - VITE_API_BASE_URL=https://backend:3000/api

networks:
  my-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data:
